#!/usr/bin/env bash
# Write src/qemu_pins.rs from a published QEMU bundle release.
#
#   packaging/qemu/pin.sh [TAG]
#
# TAG defaults to qemu-<QEMU_VERSION>-r<BUNDLE_REV> from VERSION. The archives'
# checksums are read from the .sha256 files published beside them, so the pin is
# whatever CI actually built, and the build need not be reproducible. Commit the
# result: those hashes are what make a downloaded bundle trustworthy.
set -euo pipefail

HERE="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"
# shellcheck source=VERSION
. "$HERE/VERSION"
REPO="${REPO:-ericcurtin/vmmbox}"
TAG="${1:-qemu-$QEMU_VERSION-r$BUNDLE_REV}"
OUT="$HERE/../../src/qemu_pins.rs"
TARGETS=(aarch64-apple-darwin)

die() { printf 'pin.sh: %s\n' "$*" >&2; exit 1; }

pins=""
for target in "${TARGETS[@]}"; do
	name="vmmbox-qemu-$QEMU_VERSION-r$BUNDLE_REV-$target.tar.gz"
	url="https://github.com/$REPO/releases/download/$TAG/$name.sha256"
	line="$(curl -fsSL "$url")" || die "could not fetch $url"
	hash="${line%% *}"
	[[ "$hash" =~ ^[0-9a-f]{64}$ ]] || die "$url did not start with a SHA-256: $line"
	pins+="    (\"$target\", \"$hash\"),"$'\n'
done

cat > "$OUT" <<RS
//! The QEMU bundle this vmmbox release installs.
//!
//! GENERATED by packaging/qemu/pin.sh from packaging/qemu/VERSION and a
//! release's published checksums. Do not edit by hand: the hashes are what
//! make a downloaded bundle trustworthy.

/// Upstream QEMU version in the bundle.
pub const VERSION: &str = "$QEMU_VERSION";
/// Bundle revision: bumped when only the build recipe changes.
pub const REV: u32 = $BUNDLE_REV;
/// The oldest macOS major version the bundle runs on.
pub const MIN_MACOS: u32 = $MIN_MACOS;

/// SHA-256 of each published archive, by target. A target with no entry has no
/// bundle, and vmmbox uses the QEMU it finds on the system instead.
pub const PINS: &[(&str, &str)] = &[
$pins];
RS
printf 'pin.sh: wrote %s for %s\n' "$OUT" "$TAG" >&2
